import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.scss";

const nunito = Nunito_Sans({
  subsets: ["latin"],
  variable: "--nunito-sans",
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});


export const metadata: Metadata = {
  title: "City Guesser",
  keywords: [
    "city guesser",
    "geography game",
    "guess the city",
    "AI hints",
    "Grok AI",
    "geography quiz",
    "city trivia",
    "world cities",
    "geography challenge",
    "learn geography",
    "city trivia game",
    "guessing game",
    "interactive quiz",
    "educational game",
    "fun geography game",
    "city exploration",
    "world landmarks",
    "city landmarks",
    "geography learning",
    "city facts",
    "geography education",
  ],
  authors: [
    {
      name: "Vadym Orlov",
      url: "https://iamorlov.com",
    },
  ],
  creator: "Vadym Orlov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
